### ISSUE TITLE
Add following libraries

### ISSUE THREAD

**Issue by basickarl** [josephmisiti/awesome-machine-learning#128]
The following has a list of ML libraries you may want to add to your list.

https://github.com/mil-tokyo

**Comment by basickarl** [comment]
Also the following exist:

http://harthur.github.io/clusterfck/

http://code.google.com/p/figue/

**Comment by josephmisiti** [comment]
can you send this in a pull request in the correct places?

**Comment by basickarl** [comment]
Done!
