### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [josephmisiti/awesome-machine-learning#130]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by kusur** [comment]
I think it's a great idea. Finding a good OSS to work is usually the first
problem faced by novice contributors. Creating a centralized repository of
such softwares would help the to-be contributors.

On Tue, Apr 7, 2015 at 6:48 PM, Jeffrey Jackson <notifications@github.com>
wrote:

> We are creating a github org for all awesome open source repos. I am
> working with a few individuals who are also managing their own awesome
> repos, and I think to gain more traction we need to work together. What are
> your thoughts about collectively moving your awesome repos to
> https://github.com/AwesomeOpenSource
>
> The idea is that visibility for these repos would be increased due to more
> traffic to the org. What are your thoughts? Let me know if there is
> anything you'd like to discuss!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/josephmisiti/awesome-machine-learning/issues/130>.
>

-- 

<http://www.somaiya.edu>             <http://www.somaiya.edu/kjsmc>  
<http://www.nareshwadi.org> <http://www.somaiya.edu>  
<http://www.helpachild.in> <http://www.somaiya.edu>
