### ISSUE TITLE
opengm should appear in C++/Python

### ISSUE THREAD

**Issue by hanslovsky** [josephmisiti/awesome-machine-learning#147]
OpenGM is listed as LUA library because of the LUA wrappers that are available on github. OpenGM is written in C++ and in the official version has rather nice Python bindings, thus it should be listed under C++ and Python, referencing either the [github page](https://github.com/josephmisiti/awesome-machine-learning) or the [project website](http://hci.iwr.uni-heidelberg.de/opengm2/).

PS: Great compilation!

**Comment by josephmisiti** [comment]
cool - but can you please create a pull request instead with this lib inserted in the correct area of the doc - thank you!
