### ISSUE TITLE
Mark for unmaintained/deprecated libraries

### ISSUE THREAD

**Issue by icoxfog417** [josephmisiti/awesome-machine-learning#206]
I think we need the annotation for unmaintained/deprecated libraries.
For example, [brain](https://github.com/harthur/brain), neural networks library for JavaScript, is not maintained now.

So it will be worth to mark it like "[W]" (W means warning) or "[UNMAINTAINED]", etc.

**Comment by chezou** [comment]
Sounds nice.
But how can we guess which deprecated project or inactive stable one?

**Comment by chezou** [comment]
Sorry, I looked brain's description.
It is reasonable to annotate libraries which author says deprecated. :+1:

**Comment by josephmisiti** [comment]
Sounds good to me also.

**Comment by icoxfog417** [comment]
@josephmisiti Thank you for the replay.

Next, I think we have to think about the definition of "unmaintained/deprecated".

1. Repository's owner explicitly say that "this library is not maintained".
2. Not committed for long time (2~3 years?)

There is a idea that unless the owner shows the will, we do not mark it (1 only). 
But some repositories are not committed for long time... So it is difficult problem, and we need the criteria to do it.

**Comment by josephmisiti** [comment]
Sorry for the delay, I think (2) makes more sense.

**Comment by icoxfog417** [comment]
Sorry for the long waiting time.
I added the description about deprecated repository on the top of the README (Pull #251).

**Comment by icoxfog417** [comment]
Thank you for your quick action!
