### ISSUE TITLE
Confused which to take

### ISSUE THREAD

**Issue by aakash1492** [josephmisiti/awesome-machine-learning#286]
Hello sir,
I am working on kaldi, and i was planning to do machine learning( building dictionary after if suppose my speeched text comes wrong ) so that it dont show wrong word on again utterance. Can any one suggest me what toolkit i should use along with kaldi so that i can work efficiently. I am new to this field.
Thanx alot

**Comment by kuchaguangjie** [comment]
@aakash1492 I think this is a great question, they give so many choice, it makes it more confusing.
