### ISSUE TITLE
sort libraries in the sense of usage

### ISSUE THREAD

**Issue by mehrdaad** [josephmisiti/awesome-machine-learning#305]
Hi, instead of sorting libs and frameworks based on which language they are being implemented it would be nice to sort them there application so it would be sorted like classifiers, recommender systems, so on.

**Comment by TiberiumPY** [comment]
No, this would become harder to find libraries for your language

**Comment by mehrdaad** [comment]
@TiberiumPY typically users look for libraries based on use case rather than language.

**Comment by petacat** [comment]
You could add a tag like description under each library name. You could than use the browsers page search to go through them.

**Comment by josephmisiti** [comment]
@petacat @mehrdaad I'm cool with tags, I was planning on adding a web UI to this database we are  building anyways, so they would be useful there also.
