### ISSUE TITLE
404 error for PRML

### ISSUE THREAD

**Issue by LancelotHolmes** [josephmisiti/awesome-machine-learning#336]
as is told in the title,the resource of PRML `Pattern Recognition and Machine Learning` is not found

**Comment by josephmisiti** [comment]
send me a pull request please. thanks!

**Comment by LancelotHolmes** [comment]
Okay,I replace it with a new and valid resource,maybe you'd like to check it 
            On 12/09/2016 22:44, Joseph Misiti wrote:send me a pull request please. thanks!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/josephmisiti/awesome-machine-learning","title":"josephmisiti/awesome-machine-learning","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/josephmisiti/awesome-machine-learning"}},"updates":{"snippets":[{"icon":"PERSON","message":"@josephmisiti in #336: send me a pull request please. thanks!"}],"action":{"name":"View Issue","url":"https://github.com/josephmisiti/awesome-machine-learning/issues/336#issuecomment-266029726"}}}
