### ISSUE TITLE
Text classification to .NET

### ISSUE THREAD

**Issue by silvacaio** [josephmisiti/awesome-machine-learning#380]
I am doing a software to classify texts about health.
So, I have many texts classified in "positive" and "negative" and these are the texts for my training.
The user will put the new texts and my software will evaluate and say with this text is "positive" or "negative".
Today, I use Weka and Naïve Bayes to this, but I would like of a framework specific to .NET.

I have found Accord.NET and Encog, but I have not found a sample to text classification.

Are there others frameworks tha Can help me with this?
Thanks

**Comment by josephmisiti** [comment]
Sorry, I cannot help. I just maintain the project.
