### ISSUE TITLE
Add 19Q machine learning game

### ISSUE THREAD

**Issue by fulldecent** [josephmisiti/awesome-machine-learning#395]
I humbly submit 19Q for your consideration:

https://github.com/fulldecent/19-questions

It is a question-and-answer game implemented in PHP which uses a simple machine learning implementation. The learning happens through Bayesian inference, or a MxN neural network, depending on how you look at it.

But the fun part is that it is a game, and it is one you have already played before.

**Comment by fulldecent** [comment]
(Asking as a issue and not a PR because I didn't want to make a new category and I'm not sure where to file this.)

**Comment by josephmisiti** [comment]
sorry i missed this . - please send me a pull request

**Comment by fulldecent** [comment]
Thank you, added in https://github.com/josephmisiti/awesome-machine-learning/pull/523
