### ISSUE TITLE
Add Podcasts

### ISSUE THREAD

**Issue by gwenf** [josephmisiti/awesome-machine-learning#427]
Can we add a list of Machine Learning podcasts to this repo?

**Comment by Anirudh257** [comment]
http://www.thetalkingmachines.com
    http://lineardigressions.com
    https://twimlai.com
These are few of the brilliant podcasts in machine learning.

**Comment by gwenf** [comment]
Let's close this since it's already added in the [blogs readme](https://github.com/josephmisiti/awesome-machine-learning/blob/master/blogs.md) here.
