### ISSUE TITLE
May I translate this project into Korean?

### ISSUE THREAD

**Issue by SoYoungCho** [josephmisiti/awesome-machine-learning#505]
Hi :) I am So Young Cho, a university student in Kwangwoon University, Korea.

I am working on a project translating useful informations related to Machine Learning.
I've found this amazing repo 'awesome-machine-learning' and I think this can help a lot of Koreans who are interested in ML.

So, may I translate these infos in to Korean?
If I could, plz tell me how I can share the translated results.
Thank you :)

**Comment by BoogunChoi** [comment]
Dear So Young Cho

Hi, thank yoy for reaching to my husbands’s email. Unfortunately, he is not able to respond your email because he is in military service at the moment. I’m sorry about any inconvenience if may have caused.

Best
BG’s wife

________________________________

**Comment by josephmisiti** [comment]
@SoYoungCho I assume you are talking about the readme file? sure thing, please send me a pull request
