### ISSUE TITLE
Add FluxML and JuliaText packages in Julia

### ISSUE THREAD

**Issue by Ayushk4** [josephmisiti/awesome-machine-learning#605]
Flux is a machine learning library written entirely in Julia refer - https://fluxml.ai/

JuliaText provides with packages such as Embeddings.jl and CorpusLoaders.jl, refer - https://github.com/JuliaText/Embeddings.jl that are used in Machine Learning to load datasets and word embeddings.

**Comment by josephmisiti** [comment]
please send me a PR. thanks!
