### ISSUE TITLE
Tracking experiments

### ISSUE THREAD

**Issue by escorciav** [josephmisiti/awesome-machine-learning#644]
Hi!

Thanks for maintaining this. You may wanna take a look at the tools mentioned in [this tweet](https://twitter.com/3scorciav/status/1185297245958234112).

- I tried my best to compile all the tools mentioned in the comments.
- Three of them are reviewed [here](https://www.inovex.de/blog/machine-learning-model-management/).

Perhaps, they could be included in this [section](https://github.com/josephmisiti/awesome-machine-learning#tools).

**Comment by escorciav** [comment]
Hi @josephmisiti , could u pls gimme a 👍 (or 👎 ) and I'll submit the PR?

**Comment by josephmisiti** [comment]
sure, send me a PR>
