### ISSUE TITLE
Add an AI safety section

### ISSUE THREAD

**Issue by aidanjungo** [josephmisiti/awesome-machine-learning#910]
I think it would be good to add a section on safety and ethics of AI. Many interesting applications can be produced with machine learning but it also raises many ethical and technical questions. There is also some research on the subject (not enough unfortunately) and it would be good to make it more attractive. 
Here are some examples of topics I could think of: 

- Machine learning security (evasion, poisoning, 51% attack)
- Recommendation algorithms, collaborative filtering
- Alignment issues
- Privacy and compliance issues

**Comment by josephmisiti** [comment]
send me a PR please!
